config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # get '/customers', to 'customers', as: 'customers'
  get '/', to: 'customers#index', as: 'index'
  get '/alphabetized', to: 'customers#alphabetized', as: 'alphabetized'
  get '/missing_email', to: 'customers#missing_email', as: 'missing_email'

  root to: 'home#index'
  resources :customers, only: [:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  validate :full_name, :phone, :email, :notes

  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :Customers
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers= Customer.where(:email => "")
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customers.html.erb

<div>
  <% @customers.each do |customer| %>
    <div class="customer">
      <h3>Name: <%= customer.full_name %></h3>
      <%= image_tag customer.image, :class =>"img" %></br>
      <% if !customer.province.nil?%>
         <p>Province: <%=customer.province.name %></p>
       <%else%>
          <p>Province: None</p>
       <%end%>
      <p><%= customer.phone %></p>
      <p><%= customer.email %><br></p>
    </div>
  <% end %>
</div>

app/views/customers/alphabetized.html.erb
<%= render partial: 'menu/menu' %>

<h1>All Customers ordered by Name</h1>
<%= render partial: 'customers', object: @customers %>

app/views/customers/index.html.erb
<%= render partial: 'menu/menu' %>
<h1>All Customers</h1>

<%= render partial: 'customers', object: @customers %>

app/views/customers/missing_email.html.erb
<%= render partial: 'menu/menu' %>
<h1>All Customers missing email information</h1>
<%= render partial: 'customers', object: @customers %>

app/views/menu/_menu.html.erb
<h1>
  <%= link_to 'index' , index_path %>
  <%= link_to 'alphabetized' , alphabetized_path %>
  <%= link_to 'missing emails' , missing_email_path %>
</h1>
</br>